export const content = {
    Popular:  [
        "Enchanting forest path",
        "Vibrant city skyline",
        "Snow-covered winter wonderland",
        "Lush green meadow",
        "Historical ancient ruins",
        "Sun-kissed beach scene",
        "Starry night sky",
        "Whimsical fairytale castle",
        "Urban street art",
        "Tranquil garden pond",
        "Vibrant street market",
        "Peaceful riverbank",
        "Majestic wildlife safari",
        "Magical underwater world",
        "Serene zen garden",
        "Mystical moonlit landscape",
        "Vintage retro vibes",
        "Dreamy pastel colors",
        "Dramatic thunderstorm",
        "Playful children at play",
        "Majestic mountain range",
        "Colorful autumn foliage",
        "Breathtaking coastal cliffs",
        "Serene lakeside view",
        "Idyllic countryside landscape",
        "Tranquil waterfall oasis",
        "Majestic Gothic cathedral",
        "Cozy mountain cabin",
        "Rustic barn landscape",
        "Golden hour",
        "Colorful garden",
        "Neon lights",
        "Foggy atmosphere",
        "Mysterious foggy alley",
        "Cloudy skies",
        "Smoky haze",
        "Tropical bird",
        "Cute cat",
        "Fluffy animal",
        "Beautiful woman",
        "Dancing flames",
        "Flickering fire"
    ],
    Quality : [
        "High-definition",
        "Premium",
        "Superior",
        "Professional",
        "Flawless",
        "Exquisite",
        "Craftsmanship",
        "Unparalleled",
        "High-end",
        "Photorealistic",
        "Textured",
        "Fine art",
        "Impressive",
        "Immersive",
        "Hyperrealistic",
        "High-resolution",
        "Lifelike",
        "Masterpiece",
        "Detailed brushwork",
        "Multi-layered",
        "Real-time rendering",
        "Ambient occlusion",
        "Global illumination",
        "Atmospheric effects",
        "Reflections",
        "Shadows",
        "Composition",
        "Symmetry",
        "Subtle gradients",
        "Color harmony",
        "High dynamic range (HDR)",
        "PBR (Physically Based Rendering)",
        "Specular highlights",
        "Translucency",
        "Noise reduction",
        "Post-processing effects",
        "Naturalistic",
        "Otherworldly",
        "Fantasy",
        "Magical",
        "Dreamlike",
        "Aesthetic",
        "Transcendent",
        "Mesmerizing",
        "Enchanting",
        "Captivating",
        "Thought-provoking",
        "Expressive",
        "Evocative",
        "Mind-bending",
        "Interactive",
        "3D modeling",
        "Sculptural forms",
        "Organic textures",
        "Architectural design",
        "Urban landscapes",
        "Nature-inspired",
        "Sci-fi",
        "Cyberpunk",
        "Steampunk",
        "Abstract",
        "Minimalist",
        "Pop art",
        "Conceptual",
        "Collage",
        "Experimental",
        "Multidimensional",
        "Timeless",
        "Haunting",
        "Emotive",
        "Dynamic composition",
        "Fluid motion",
        "Ethereal",
        "Mystical",
        "Symbolic",
        "Highly detailed",
        "Details",
        "Octane render",
        "HD",
        "8K",
        "Unreal engine",
        "Ray tracing",
        "VRay",
        "High quality",
        "Ultra detailed",
        "Detailed matte painting",
        "Stunning visuals",
        "Iridescent accents",
        "Vibrant",
        "Creative",
        "Elegant",
        "Intricate",
        "Smooth",
        "Full HD",
        "Depth of field",
        "Wallpaper",
        "Studio light",
        "Cinematic lighting",
        "Cinematic",
        "Realistic lighting",
        "Soft lighting",
        "Dynamic lighting",
        "Centered",
        "Sharp focus",
        "Panoramic",
        "Volumetric light",
        "Uplight"
    ],
    Styles:[
        "Minimalism",
        "Street art",
        "Graffiti",
        "Abstract",
        "Portraits",
        "Landscape",
        "Still life",
        "Wildlife",
        "Nature",
        "Architecture",
        "Character design",
        "Sci-fi",
        "Anime",
        "Manga",
        "Comic book",
        "Graphic novel",
        "Typography",
        "Calligraphy",
        "Mixed media",
        "Collage",
        "Mosaic",
        "Sculpture",
        "Ceramic art",
        "Glass art",
        "Installation art",
        "Performance art",
        "Kinetic art",
        "Interactive art",
        "Video art",
        "Sound art",
        "Generative art",
        "Algorithmic art",
        "Data visualization",
        "Augmented reality",
        "Virtual reality",
        "Motion graphics",
        "Music-inspired",
        "Fashion-inspired",
        "Botanical",
        "Underwater",
        "Celestial",
        "Cityscape",
        "Abstract expressionism",
        "Cubism",
        "Dadaism",
        "Fauvism",
        "Constructivism",
        "Land art",
        "Street photography",
        "Documentary photography",
        "Fashion photography",
        "Still photography",
        "Macro photography",
        "High-speed photography",
        "Long exposure photography",
        "Black and white photography",
        "Infrared photography",
        "Experimental photography",
        "Nature photography",
        "Wildlife photography",
        "Concept art",
        "Digital painting",
        "Oil painting",
        "3D",
        "Drawing",
        "Sketch",
        "Watercolor",
        "Cartoon",
        "Vintage",
        "Aesthetic",
        "Illustration",
        "Pointillism",
        "Pop art",
        "Bokeh",
        "Black and White",
        "Psychedelic",
        "Texture",
        "Brush effect",
        "Cyberpunk",
        "Background",
        "Futuristic",
        "Steampunk",
        "Postmodernism",
        "Surrealism",
        "Impressionism",
        "Hyperrealism",
        "Ultra-realism",
        "Trending on Artstation",
        "Artstation",
        "Dark fantasy",
        "Epic fantasy",
        "Renaissance",
        "Fantasy world",
        "Fantasy",
        "Oriental art"
    ],
    Color:[
        "Opalescent",
        "Metallic",
        "Prismatic",
        "Iridescent",
        "Gradient",
        "Vibrant",
        "Earth tones",
        "Subtle hues",
        "Vivid",
        "Tonal variations",
        "Warm colors",
        "Cool colors",
        "Tangerine",
        "Teal",
        "Lavender",
        "Moss green",
        "Ochre",
        "Peach",
        "Olive",
        "Coral",
        "Rustic",
        "Rusty red",
        "Sapphire",
        "Silvery",
        "Smoky",
        "Turquoise",
        "Verdant",
        "Amethyst",
        "Aquamarine",
        "Azure",
        "Blush pink",
        "Chartreuse",
        "Deep purple",
        "Maroon",
        "Mustard yellow",
        "Orchid",
        "Peachy",
        "Pistachio",
        "Plum",
        "Scarlet",
        "Analogue colors",
        "Bronze",
        "Burgundy",
        "Canary yellow",
        "Cobalt blue",
        "Colorful",
        "Coral pink",
        "Crimson red",
        "Cyan",
        "Deep colors",
        "Golden",
        "Duotone",
        "Electric violet",
        "Fluorescent orange",
        "Glitter",
        "Holographic",
        "Indigo",
        "Ivory Lime Green",
        "Magenta",
        "Mauve",
        "Monochromatic",
        "Nacre color",
        "Neon colors",
        "Pale lilac",
        "Pastel colors",
        "Pearly",
        "Periwinkle",
        "Rich colors",
        "Rose Gold",
        "Sepia colors"
    ],
    Artist: [
        "Rembrandt",
        "Claude Monet",
        "Pierre-Auguste Renoir",
        "Edgar Degas",
        "Paul Cézanne",
        "Vincent van Gogh",
        "Henri Matisse",
        "Wassily Kandinsky",
        "Pablo Picasso",
        "Georges Braque",
        "Henri Rousseau",
        "Marc Chagall",
        "Jackson Pollock",
        "Mark Rothko",
        "Salvador Dalí",
        "Joan Miró",
        "René Magritte",
        "Frida Kahlo",
        "Piet Mondrian",
        "Paul Klee",
        "Roy Lichtenstein",
        "Andy Warhol",
        "Jean-Michel Basquiat",
        "Damien Hirst",
        "Banksy",
        "William Waterhouse",
        "Albert Bierstadt",
        "Alphonse Mucha",
        "Martine Johanna",
        "Thomas Kinkade",
        "Jose Daniel",
        "Shaun Tan",
        "Jonathan Solter",
        "Alena Aenami",
        "Android Jones",
        "Hokusai",
        "Makoto Shinkai",
        "Diego Gisbert",
        "Georgia O'Keeffe",
        "Kazimir Malevich",
        "Egon Schiele",
        "Gustav Klimt",
        "Edvard Munch",
        "Johannes Vermeer",
        "Francisco Goya",
        "Sandro Botticelli",
        "Michelangelo"
    ],
    Mood:[
        "Serene",
        "Vibrant",
        "Mysterious",
        "Tranquil",
        "Surreal",
        "Magical",
        "Futuristic",
        "Serendipitous",
        "Captivating",
        "Luminous",
        "Mystical",
        "Evocative",
        "Enigmatic",
        "Dynamic",
        "Peaceful",
        "Enthralling",
        "Sublime",
        "Ethereal",
        "Soothing",
        "Intriguing",
        "Mesmerizing",
        "Abstract",
        "Lively",
        "Breathtaking",
        "Harmonious",
        "Dreamy",
        "Awe-inspiring",
        "Thought-provoking",
        "Intense",
        "Melancholic",
        "Melancholy",
        "Romantic",
        "Emotional",
        "Energetic",
        "Joyful",
        "Nostalgic",
        "Uplifting",
        "Epic",
        "Calm",
        "Moody",
        "Dark",
        "Dramatic",
        "Playful",
        "Whimsical",
        "Gloomy",
        "Hypnotic",
        "Immersive",
        "Sensual",
        "Sensory",
        "Intimate",
        "Reverie",
        "Contemplative",
        "Reflective",
        "Wistful",
        "Lyrical",
        "Fanciful",
        "Adventurous",
        "Delicate",
        "Dynamic",
        "Ebullient",
        "Ecstatic",
        "Effervescent",
        "Expansive",
        "Exuberant",
        "Fervent",
        "Fresh",
        "Impressionistic",
        "Jubilant",
        "Lively",
        "Nimble",
        "Radiant",
        "Resplendent",
        "Sprightly",
        "Sunny",
        "Thrilling",
        "Vital",
        "Vivacious",
        "Wholesome",
        "Zesty"
    ]
}
